# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b360ae9855c365dc797d31f8f6ef71a4d80d21b062cc660283628627e9daf99ce37feb33cf2a14a40a767bf7f1c41f4d72efaab335a93e71b822a35b337d25

test:
  secret_key_base: d61e715162bea6952bf906b3e84f08745bc33ab42e18c627b299b06e816e242c2c9a5885075c6f12adb5aafe275c80ce4b344c79744a26a20eee0fec40a6fa2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
